[package]
name = "game_of_life"
version = "0.1.0"
description = "The Game of Life in Tui Form"
authors = ["Connor-Kelly <connorkelly726@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = {version= "0.29.0", features= []}
color-eyre = "0.6.3"
rand = "0.9.2"
